# Generated by Django 5.1.1 on 2024-09-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
            ],
        ),
    ]
